---
title: OldTyT
paginate: 5
theme: hugo-papermod
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
minify:
  disableXML: true
  minifyOutput: true
languages:
  en:
    languageName: "English üá∫üá∏"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    params:
      languageAltTitle: English
      profileMode:
        enabled: true
        title: OldTyT
        imageUrl: 'https://gitlab.com/uploads/-/system/user/avatar/9780123/avatar.png'
        imageTitle: OldTyT
        subtitle: "üåã Work hard | üéÆ Play hard"
    menu:
      main:
        - name: CV
          url: cv
          weight: 3
        - name: Posts
          url: posts
          weight: 6
        - name: Search
          url: search
          weight: 8
        - name: Donate
          url: donate
          weight: 9
  ru:
    languageName: "Russian üá∑üá∫"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    params:
      languageAltTitle: Russian
      profileMode:
        enabled: true
        title: OldTyT
        imageUrl: 'https://gitlab.com/uploads/-/system/user/avatar/9780123/avatar.png'
        imageTitle: OldTyT
        subtitle: "üåã Work hard | üéÆ Play hard"
    menu:
      main:
        - name: –†–µ–∑—é–º–µ
          url: cv
          weight: 3
        - name: –ü–æ—Å—Ç—ã
          url: posts
          weight: 6
        - name: –ü–æ–∏—Å–∫
          url: search
          weight: 8
        - name: –î–æ–Ω–∞—Ç
          url: donate
          weight: 9
outputs:
  home:
    - HTML
    - RSS
    - JSON
params:
  icon: 'https://gitlab.com/uploads/-/system/user/avatar/9780123/avatar.png'
  description: Personal website OldTyT
  author: OldTyT
  defaultTheme: auto
  ShowShareButtons: true
  ShareButtons: ["x", "telegram"]
  ShowReadingTime: true
  disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  images:
    - papermod-cover.png
  profileMode:
    enabled: true
    title: OldTyT
    imageUrl: '#'
    imageTitle: My avatar
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags
  socialIcons:
    - name: telegram
      url: 'https://t.me/oldi_na_meste'
    - name: github
      url: 'https://github.com/OldTyT'
    - name: gitlab
      url: 'https://gitlab.com/OldTyT'
  editPost:
    URL: 'https://gitlab.com/OldTyT/oldtyt.xyz/blob/master/content'
    Text: Suggest Changes
    appendFilePath: true
  analytics:
    google:
      SiteVerificationTag: G-2Q1PY6PFPY
  assets:
    disableHLJS: true
    favicon: 'https://gitlab.com/uploads/-/system/user/avatar/9780123/avatar.png'
    apple_touch_icon: 'https://gitlab.com/uploads/-/system/user/avatar/9780123/avatar.png'
    safari_pinned_tab: 'https://gitlab.com/uploads/-/system/user/avatar/9780123/avatar.png'
  cover:
    linkFullImages: true
    responsiveImages: true
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
privacy:
  vimeo:
    disabled: false
    simple: true
  twitter:
    disabled: false
    enableDNT: true
    simple: true
  instagram:
    disabled: false
    simple: true
  youtube:
    disabled: false
    privacyEnhanced: true
services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
